### ISSUE TITLE
Selection of assets to use randomly and metadata export

### ISSUE THREAD

**Issue by CptJackieSparrow** [ephread/Autodazzler#15]
Hey there! Awesome project!

So is it possible that the script should do following tasks:
- Allow us to select the assets that’ll be included in the collection. (Pretty cool if it'll have a GUI for me to select like the following image)
- Allow us to select how many renders in the end result (10-50), and calculate how many characters can be made in total with the selected assets.
- Every render should be unique, no duplicates (Renders can share the assets, but no avatar can be the same %100)
- Can it create a metadata and export it as a json file format after each render. This metadata should contain all the objects rendered on the scene (like hat's name, sunglass name... basicly all objects name on the scene)?
- Render each character individually, save them with the name I chose (Like Render_1, Render_2, Render_3 or Human_1, Human_2, or Character#1, Character#2 etc.)
- Save every character as DAZ3D format for further tweaking with the same name as rendered image (somethings can be messy with the automated script rendering, so going to file and manually solving the issue)

**Comment by ephread** [comment]
> Awesome project!

Thanks but I won’t support NFTs and other crypto scams.
